// countryToRegion.ts
export const countryToRegion: Record<string, string> = {
  "Afghanistan": "Asia",
  "Albania": "Europe",
  "Algeria": "Africa",
  "Andorra": "Europe",
  "Angola": "Africa",
  "Argentina": "Americas",
  "Australia": "Oceania",
  "Austria": "Europe",
  "Bangladesh": "Asia",
  "Belgium": "Europe",
  "Brazil": "Americas",
  "Canada": "Americas",
  "Chile": "Americas",
  "China": "Asia",
  "Colombia": "Americas",
  "Congo (Brazzaville)": "Africa",
  "Denmark": "Europe",
  "Egypt": "Africa",
  "Finland": "Europe",
  "France": "Europe",
  "Germany": "Europe",
  "Greece": "Europe",
  "India": "Asia",
  "Indonesia": "Asia",
  "Iran": "Asia",
  "Iraq": "Asia",
  "Ireland": "Europe",
  "Israel": "Asia",
  "Italy": "Europe",
  "Jamaica": "Americas",
  "Japan": "Asia",
  "Kenya": "Africa",
  "Kuwait": "Asia",
  "Lebanon": "Asia",
  "Malaysia": "Asia",
  "Mexico": "Americas",
  "Morocco": "Africa",
  "Netherlands": "Europe",
  "New Zealand": "Oceania",
  "Nigeria": "Africa",
  "Norway": "Europe",
  "Oman": "Asia",
  "Pakistan": "Asia",
  "Panama": "Americas",
  "Peru": "Americas",
  "Philippines": "Asia",
  "Poland": "Europe",
  "Portugal": "Europe",
  "Qatar": "Asia",
  "Russia": "Europe",
  "Saudi Arabia": "Asia",
  "Singapore": "Asia",
  "South Africa": "Africa",
  "South Korea": "Asia",
  "Spain": "Europe",
  "Sri Lanka": "Asia",
  "Sweden": "Europe",
  "Switzerland": "Europe",
  "Thailand": "Asia",
  "Turkey": "Europe",
  "Uganda": "Africa",
  "Ukraine": "Europe",
  "United Arab Emirates": "Asia",
  "United Kingdom": "Europe",
  "United States": "Americas",
  "Venezuela": "Americas",
  "Vietnam": "Asia",
  "Zambia": "Africa",
  "Zimbabwe": "Africa"
};
